### ISSUE TITLE
Issues with early vive

### ISSUE THREAD

**Issue by cnlohr** [cntools/libsurvive#125]
It's very strange but it looks like the Z and X sensor coordinates have been flipped, but perhaps also the z/x gravity vector, but that's difficult to determine. 

[axlecrushers_vive.txt.zip](https://github.com/cnlohr/libsurvive/files/1878514/axlecrushers_vive.txt.zip)

**Comment by jdavidberger** [comment]
I think we handle this properly now; but don't have an early vive to test on. Closing until someone says otherwise....
