### ISSUE TITLE
'survive-cli' does not work at all, 'calibrate' does

### ISSUE THREAD

**Issue by NicksonYap** [cntools/libsurvive#149]
Hi, 

I'm new to this project.

I'm using 2 LH BS v1 (from 2016) and HTC Vive HMD (new 2018/2019) on Ubuntu 16.04
Worked fined with SteamVR

----

With fresh installation, I tried `survive-cli` in latest master and it just keeps printing once in a while, no plot comes up and outputs:
```
Info: Uncalibrated configuration detected. Attaching calibration. Please don't move tracked objects for the duration of calibration. Pass '--disable-calibrate' to skip calibration
Info: Calibration is using HMD
Info: Locked onto state 11(2, 20032) at 218931253 for HMD
Info: OOTX not set for LH 1; attaching ootx decoder using device HMD
Info: OOTX not set for LH 0; attaching ootx decoder using device HMD
Info: (0) Preamble found
Info: (0) OOTX Decoder: Bad sync bit
Info: (1) Preamble found
Info: (1) OOTX Decoder: Bad sync bit
Info: (1) Preamble found
Info: (1) OOTX Decoder: Bad sync bit
Info: (1) Preamble found
Info: (1) OOTX Decoder: Bad sync bit
Info: (0) Preamble found
Info: (0) OOTX Decoder: Bad sync bit
Info: (1) Preamble found
Info: (1) OOTX Decoder: Bad sync bit
... (and so on, non stop)
```

----
Managed to get it working with older commit: d9a5da84672ac74fb8c188aca900abf68712d24b (before `calibrate` was removed)

Note that even in old commit SBA and EPNP poser worked flawlesly, but MPFIT did not work and gave rather odd error:
```
Info: Can't solve for cameras with just 0 measurements
```

----

I tried `survive-cli` in that commit and the latest master, neither works.

Could it be something to do with the disambiguator?
In master `survive-cli` Turvey disambiguator repetitively prints:

```
Warning: Disambiguator gave invalid timeinsweep HMD 579700
Warning: Disambiguator gave invalid timeinsweep HMD 580537
Warning: Disambiguator gave invalid timeinsweep HMD 580201
Warning: Disambiguator gave invalid timeinsweep HMD 581400
Warning: Disambiguator gave invalid timeinsweep HMD 581232
``` 

Turvey disambiguator worked in the older commit mentioned just now

----

Believing that master has issue getting OOTX data, I've also tried "transplanting" config from old commit to latest master and run `simple_pose_test`. 
Using SBA, the best i could get is a static plot while the same pose values kept getting printed (HMD frozen near origin)

Using EPNP, the best i could get is very inaccurate and very slow update rate of the pose

Using MPFIT, i get:

```
Info: Parameter Pose y is invalid. -20.000000 <= -22.229569 <= 20.000000 should be true

or 

Info: Parameter Pose y is invalid. -20.000000 <= -26.518796 <= 20.000000 should be true
Info: Parameter Pose z is invalid. -20.000000 <= -31.925276 <= 20.000000 should be true

and sometimes:

Warning: Squelching reported pose of +2.388609	-24.018258	-28.826689	+0.150689	+0.547008	-0.822039	+0.048249 for HMD; values are invalid
Warning: Squelching reported pose of +2.392429	-24.064270	-28.883008	+0.150683	+0.547001	-0.822045	+0.048235 for HMD; values are invalid
Warning: Squelching reported pose of +2.423523	-24.430921	-29.334350	+0.150700	+0.546947	-0.822084	+0.048125 for HMD; values are invalid

----

Conclusion:

Generally `calibrate` worked well in old commit (worked with SBA, EPNP and BaryCentricSVD, not with MPFIT or CharlesRefine)

 `survive-cli` in both old commit and master  just gave a lot of weirdness


```

----

Off topic:

I'm actually hoping to run `poser_octavioradii.c` and `poser_turveytori.c`, however they don't seem to be selectable and just doesn't work. 

```
Info: Available Posers:
Info: 	 CharlesRefine
Info: 	 BaryCentricSVD
Info: 	 MPFIT
Info: 	 SBA
Info: 	 Dummy
Info: 	 IMU
Info: 	EPNP
```

How can we select them?

I hope my findings help, let me know if more tests or scenarios are needed!

Thanks!

**Comment by jdavidberger** [comment]
Can you make a recording of your setup on master with everything just stationary --

```
rm config.json
./survive-cli --record issue149.rec.gz
```

Let that run for maybe twenty seconds or so and then send me the file? 

It's weird that OOTX is failing in master and not at a later date. Did the HMD move in the mean time or something? Possibly there is some logic issue that is throwing it off. 

Calibrate and survive-cli will run the same calibration procedure; so I suspect there is just a difference between those two commits in the core library. survive-cli doesn't have a graphical output of its own; simple_pose_test does or you can look at the viz tool setup -- it's a little more work but its easier to see whats going on. 

poser_octavioradii and poser_turveytori haven't been updated in a while; and have some build issues currently. You'd have to fix those and re-add them to the make system. I'm not sure their implementation was ever fully finished though, so I don't know what kind of results you were hoping for with them.
