### ISSUE TITLE
No button events on USB connected Index Controller

### ISSUE THREAD

**Issue by ChristophHaag** [cntools/libsurvive#179]
A callback like
```c
void testprog_button_process(SurviveObject * so, uint8_t eventType, uint8_t buttonId, uint8_t axis1Id, uint16_t axis1Val, uint8_t axis2Id, uint16_t axis2Val) {
	survive_default_button_process(so, eventType, buttonId, axis1Id, axis1Val, axis2Id, axis2Val);
	printf("Button %d %d %d %d %d %d\n", eventType, buttonId, axis1Id, axis1Val, axis2Id, axis2Val);
}
```
prints values as expected when the Index Controller is RF connected. When connected with USB, the controller is tracked fine, but there are never any button events.

This only affects the Index Controller. The Vive Wand buttons work fine when connected with USB.

**Comment by jdavidberger** [comment]
It looks like the firmware the knuckles are based on don't output button data over USB ever. Or at least I couldn't get them to. Doesn't seem like anything in steamvr lets me do this either. 

If there is a way to get button data via USB in some other program I can libpcap it and figure out how; but I really think thats just not a thing with the knuckles.
