### ISSUE TITLE
assert(size == 29) failing on survive_data_cb_locked for VIVE_REPORT_RF_WATCHMAN

### ISSUE THREAD

**Issue by BenWoodford** [cntools/libsurvive#184]
In my setup, for whatever reason, the size is 58 which would be in line with `VIVE_REPORT_RF_WATCHMANx2`

Output: https://gist.github.com/BenWoodford/44a58196bd9afabe62445a50d2d7840c

Locals:

![image](https://user-images.githubusercontent.com/503263/76327970-9929b600-62e2-11ea-8460-d7b18f149842.png)

SteamVR's monitor view (if it helps)

![image](https://user-images.githubusercontent.com/503263/76328004-a3e44b00-62e2-11ea-95a7-edbd57f9b062.png)

Using Lighthouse 2.0, a Vive Pro, and Gen 2 trackers

**Comment by jdavidberger** [comment]
This doesn't happen anymore right?

**Comment by jdavidberger** [comment]
Usb buffers in windows are weird; assert has been removed
