### ISSUE TITLE
Unstable positioning and jitter on V2.0

### ISSUE THREAD

**Issue by Realiscape** [cntools/libsurvive#192]
So I've been trying out libsurvive to get rid of SteamVR. I like how easily I can build shared libs out of it that I can use directly in Unity or through a web layer. I only want to get accurate positions/rotations from plain trackers (up to 6-7 of them), so no HMD, controllers, gestures, rendering, or any other feature of the Vive system.

What I use:
V2 trackers, both wired and wireless
Gen2 lighthouses, from 1 besides the desk to 4 around the room (also tried Gen1)
Good lighting/reflection conditions
Fast enough Linux box, with reasonable CPU usage and USB3.0

The results I get are way worse than what I've seen is possible with this lib, and really inconsistent. At rest after calibration, jitter could be sub-1mm, sometimes 5cm, and upon movement it goes really off, or there are occasional big fluctuations, similar to IMU drifts. I mainly run api_example. Example output of a ~2min clean run with one wired tracker:
```
~/dev/libsurvive$ ./api_example | grep SimpleApi
SimpleApi: Adding tracked object T20 from HTC
SimpleApi: All enumerated devices attached.
SimpleApi: Powered unit on.
SimpleApi: Loaded drivers: HTCVive
SimpleApi: Detected LH gen 2 system.
SimpleApi: LightcapMode (T20) 1 -> 2
SimpleApi: Adding lighthouse ch 0 (idx: 0, cnt: 1)
SimpleApi: OOTX not set for LH in channel 0; attaching ootx decoder using device T20
SimpleApi: (0) Preamble found
SimpleApi: Got OOTX packet 0
SimpleApi: Attempting to solve for 0 with 17 meas
SimpleApi: Solved for 0 with error of 0.003820/0.000014
SimpleApi: Using LH 0 (d93033e6) as reference lighthouse
SimpleApi: Position found for LH 0(d93033e6)
^CSimpleApi: MPFIT stats for T20:
SimpleApi: 	seed runs         2 / 4331
SimpleApi: 	error failures    0
SimpleApi: Cleaning up interface on 7 IMU
SimpleApi: Cleaning up interface on 11 Lightcap
SimpleApi: Cleaning up interface on 15 Buttons
```

Example trail from a 30cm circular waiving around the table:
![Untitled](https://user-images.githubusercontent.com/65708750/82544591-03ba6600-9b5e-11ea-9a64-e8a8129ad715.png)

What should the calibration/startup procedure be for this kind of setup? Should I just wait per the README? Now I just remove calinfo/* and *.json and re-run one of the example apps.

Do you think I could reach SteamVR levels of accuracy? 

Thank you

**Comment by jdavidberger** [comment]
Recently the tracking has gotten a lot better and more robust especially with the tracker. I think we can reach the accuracy in steamvr; and hopefully are on our way. Please retest and see if the performance improved
