### ISSUE TITLE
calibration the azimuth and elevation

### ISSUE THREAD

**Issue by 807183087** [cntools/libsurvive#215]
Hello my friends, 
the angle minus   4 * LINMATHPI / 3     or     2 * LINMATHPI / 3    in survive_process_gen2.c.
I dont know why do this. 
And Is there a surely formula for calibration the azimuth and elevation ?
I saw a solution in https://hackaday.io/project/19570-htc-vive-lighthouse-custom-tracking/log/73662-in-your-gibbous-phase. Is it the same solution with survive ?

**Comment by jdavidberger** [comment]
I'm copying this from the discord:

> That math is modeling the physicality of the gen 2 lighthouse
> Its translating the rotor rotation into a standard range and determining which laser plane it is
> Calibration details happen later. The calibration model vive uses is not a correction to observed angles; instead it predicts observed angles from a given location in 3d space
> Azimuth and elevation are kind of direct in gen1, but the gen 2 system has the sweep planes at an angle and they are not 90 degrees offset from eachother
