### ISSUE TITLE
quatfind_between_vectors - walking out of memory

### ISSUE THREAD

**Issue by joejarvis64** [cntools/libsurvive#218]
**Describe the bug**
I was running a test and found that the tmp variable from the function below is not big enough when you go through the if (d < -.999)  branch.  The tmp variable is 3 doubles but the quat routines that it calls require 4 so that causes it to walk over memory.

I am not really sure how to fix this though so hoping for an assist.  Perhaps the cross3d/norm3d routines should just work on the x,y,z of a quat.  But then calling normalize seems a bit odd since it is not really a quat at that point.

`void quatfind_between_vectors(LinmathQuat q, const LinmathPoint3d _p0, const LinmathPoint3d _p1) {
	LinmathPoint3d p0, p1;
	normalize3d(p0, _p0);
	normalize3d(p1, _p1);

	FLT d = dot3d(p0, p1);

	if (d < -0.999999) {

	} else if (d
	> 0.999999) {
		LinmathPoint3d tmp, xUnit = {1, 0, 0}, yUnit = {0, 1, 0};
		cross3d(tmp, xUnit, p0);
		if (norm3d(tmp) < .00001)
			cross3d(tmp, yUnit, p0);
		quatnormalize(tmp, tmp);
		quatscale(tmp, tmp, LINMATHPI);

		quatfromaxisanglemag(q, tmp);
	} else {
		cross3d(q + 1, p0, p1);
		q[0] = 1 + d;
		quatnormalize(q, q);
	}
}`

**Comment by jdavidberger** [comment]
Thanks for pointing that out, fixed in: https://github.com/cntools/libsurvive/commit/f28fce88380eeebefb896b4bb440fa7ddb4d04da
