### ISSUE TITLE
kalman imu scale issue?

### ISSUE THREAD

**Issue by joejarvis64** [cntools/libsurvive#227]
https://github.com/cntools/libsurvive/blob/d47c15a6a788e50092e936224332ddd6b911c216/src/survive_kalman_tracker.c#L279

On this line of code, it will set w to a moving or stationary scale.  However, it checks SurviveSensorActivations_stationary_time() > .1.  The return from SurviveSensorActivations_stationary_time is in ticks, not seconds.  So this will always pick up on the stationary scale.

Am I mis-reading this?

**Comment by jdavidberger** [comment]
:facepalm: You are correct; I remember being surprised when I was testing this that it was so sensitive. I need to test the fix before I push it though.
