### ISSUE TITLE
How many base stations (Lighthouse 2.0) can be stacked together to cover a really wide area for tracking? 

### ISSUE THREAD

**Issue by garbage98** [cntools/libsurvive#228]
**Describe the bug**

**Data**
For tracking or device specific issues, it is incredibly helpful if you could provide us with a data log of the issue. See the [readme](https://github.com/cntools/libsurvive#data-recording) for how to do that.

**Compile log**
If the issue is a compilation issue, please provide a log of the compiler output; as well as what compiler you are using. 
**Hardware setup**
Please include the hardware setup, such as what devices you are using and which version of lighthouse you are using (The rounded face base stations are version 2, the flat face base stations are version 1). 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, Linux]

**Additional context**

**Comment by JohanVer** [comment]
I am also curious about this. Does anybody know?

**Comment by BenWoodford** [comment]
16 as there’s no special handling for overlapping channels right now, IIRC?

**Comment by jdavidberger** [comment]
It is 16 currently
