### ISSUE TITLE
Make error: Configuring incomplete

### ISSUE THREAD

**Issue by utsavrai** [cntools/libsurvive#229]
After following given steps, while doing "make" following error appears:

mkdir -p bin
cd bin && cmake .. && cmake --build . 
Found cblas at /usr/lib/x86_64-linux-gnu/libcblas.so
Found openblas at /usr/lib/x86_64-linux-gnu/libopenblas.so
Found lapacke at /usr/lib/x86_64-linux-gnu/liblapacke.so
Searching for 'cblas.h'; found at /usr/include/x86_64-linux-gnu/cblas.h
Using blas backend /usr/lib/x86_64-linux-gnu/libcblas.so
Using versioned libusb dir
Can't build usbmon plugin -- pcap library was not found
-- Using CATKIN_DEVEL_PREFIX: /home/utsav/libsurvive/devel
-- Using CMAKE_PREFIX_PATH: /home/utsav/workspace/devel;/opt/ros/melodic
-- This workspace overlays: /home/utsav/workspace/devel;/opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/utsav/libsurvive/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
CMake Warning (dev) at tools/ros_publisher/CMakeLists.txt:2 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
This warning is for project developers.  Use -Wno-dev to suppress it.

/opt/ros/melodic/include/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp/usr/include
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENVR_INCLUDE_PATH
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src
   used as include directory in directory /home/utsav/libsurvive/src

-- Configuring incomplete, errors occurred!
See also "/home/utsav/libsurvive/CMakeFiles/CMakeOutput.log".
See also "/home/utsav/libsurvive/CMakeFiles/CMakeError.log".
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by jdavidberger** [comment]
This looks like it's due to a bad melodic installation; although I have changed some of the ROS integration option recently and this might be resolved for melodic.
