### ISSUE TITLE
valgrind errors

### ISSUE THREAD

**Issue by ChristophHaag** [cntools/libsurvive#230]
Archlinux, Valve Index + Index Controllers

running with valgrind shows several invalid writes in driver_vive.libusb.h:252, then valgrind crashes.

[valgrind_api_example.txt](https://github.com/cntools/libsurvive/files/6101292/valgrind_api_example.txt)

**Comment by jdavidberger** [comment]
This _shouldnt_ happen in the latest; I run it with address sanitizer and it reports no issues.
