### ISSUE TITLE
occasional "Assertion `timeIndex % 2 == 1' failed."

### ISSUE THREAD

**Issue by ChristophHaag** [cntools/libsurvive#248]
libsurvive/src/driver_vive.c:1572: read_light_data: Assertion `timeIndex % 2 == 1' failed.

This happens randomly, as far as I can tell only on startup. On the next start of the app it's usually fine. Instead of asserting it would be nice to handle this gracefully.

**Comment by bl4ckb0ne** [comment]
I'm experiencing the same issue, restarting the application usually fixes it.

**Comment by jdavidberger** [comment]
Should be fixed in latest
