### ISSUE TITLE
Will python binding support the arm platform?

### ISSUE THREAD

**Issue by linjie0928** [cntools/libsurvive#249]
**Describe the bug**
I encountered difficulties when installing python binding. I hope pysurvive can support Arm-based platforms, such as Raspbian.

**Desktop (please complete the following information):**
 - OS: Raspbian

**Comment by jdavidberger** [comment]
I've added aarch64 wheels to the pip repo; let me know if those don't work for some reason. This is also in CI now so they will roll out with new commits.
