### ISSUE TITLE
config.json invalid JSON

### ISSUE THREAD

**Issue by jleppert** [cntools/libsurvive#254]
The generated config file JSON (default location: ~.config/libsurvive/config.json) is invalid JSON, at least for me. Everything is working as intended and I re-generated the file several times and the output is consistent.

Is this intention behavior? Would you accept a patch to fix the config file to make it parseable as standard JSON?

`"v":"0",
"poser":"MPFIT",
"disambiguator":"StateBased",
"configed-lighthouse-gen":"2",
"ootx-ignore-sync-error":"0"
"lighthouse0":{
"index":"0",
"id":"3077256778",
"mode":"0",
"pose":["-0.330160102039","-1.276552552457","1.193213454157","-0.905849214640","-0.419068051323","0.009939740225","0.060994837985"],
"unlock_count":"0",
"accel":["2.000000000000","127.000000000000","108.000000000000"],
"fcalphase":["0.000000000000","-0.000258684158"],
"fcaltilt":["-0.056579589844","0.046051025391"],
"fcalcurve":["0.397949218750","0.557128906250"],
"fcalgibpha":["1.542968750000","0.181030273438"],
"fcalgibmag":["0.001511573792","-0.003593444824"],
"fcalogeephase":["1.346679687500","2.347656250000"],
"fcalogeemag":["-0.272216796875","-0.250488281250"],
"OOTXSet":"1",
"PositionSet":"1"
}
"lighthouse1":{
"index":"1",
"id":"1803863242",
"mode":"1",
"pose":["0.000000000000","1.181261225374","1.193749541617","-0.021902609395","-0.027130270086","0.414698149353","0.909290750569"],
"unlock_count":"0",
"accel":["5.000000000000","127.000000000000","102.000000000000"],
"fcalphase":["0.000000000000","0.000298738480"],
"fcaltilt":["-0.048889160156","0.044403076172"],
"fcalcurve":["0.303222656250","0.523437500000"],
"fcalgibpha":["0.533691406250","2.759765625000"],
"fcalgibmag":["0.003890991211","0.002845764160"],
"fcalogeephase":["0.968261718750","2.179687500000"],
"fcalogeemag":["-0.312011718750","-0.302734375000"],
"OOTXSet":"1",
"PositionSet":"1"
}
`

**Comment by throni3git** [comment]
still the same behaviour. no surrounding curlies and missing comma between the lighthouse entries.
