### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by PureTryOut** [cntools/libsurvive#255]
I was wondering if a new release could be made. The last one was on the 22nd of October 2020 which is _more_ than a year ago and it seems _a lot_ of improvements have been made since which users have been missing out on.

**Comment by blitz-research** [comment]
I agree, I've been looking at some of the issues in the hope of helping out a bit but there's been a lot of changes to some of the key source files, esp. survive_optimize.c which seems important, hopefully for the better!

**Comment by jdavidberger** [comment]
Definitely warranted; the things blocking this is there is an oustanding USB issue I want to fix and get the groundtruth testing files in order. Hopefully will get it in today

**Comment by jdavidberger** [comment]
New version released!
