### ISSUE TITLE
libusb: microphone vanishes when starting libsurvive

### ISSUE THREAD

**Issue by ChristophHaag** [cntools/libsurvive#271]
When starting libsurvive, the microphone device vanishes:

```
pipewire[6912]: spa.alsa: hw:4: snd_pcm_drop No such device
pipewire[6912]: spa.alsa: hw:4: close failed: No such device
```

Possible reason is that libsurvive uses libusb to "claim" the usb device, same reason why steamvr doesn't find the Index after libsurvive quits.

It does not happen when compiling with `-DUSE_HIDAPI=1`.

The question is, can the microphone be exempted from the libusb device grab or is using hidapi the only viable option?

**Comment by slitcch** [comment]
We can close this now :D
