### ISSUE TITLE
Highlights reel times

### ISSUE THREAD

**Issue by cnlohr** [cntools/libsurvive#66]
For anyone who watches the livestreams, please comment in this thread when something happened you thought was interesting, so I can make a highlights reel.

Draget: 1:36:00, Livestream 10.

**Comment by geekmaster** [comment]
Playing with the window sizer at 3:07:20. ;-)

**Comment by Jimbobnz** [comment]
LIVE #10 2:56:52 - Solving the ground loop issue. - I'm bias on this one. 
https://youtu.be/8hqviGMlU7I?t=2h56m52s
