### ISSUE TITLE
Common data for project

### ISSUE THREAD

**Issue by cnlohr** [cntools/libsurvive#8]
I figured I'd make a thread for files I will be using for various static analysis tools for this project.

Config files, points and normals for my vive: [charles_all_configs.zip](https://github.com/cnlohr/libsurvive/files/660286/charles_all_configs.zip)

"Raw" lightcap data from the HMD and Watchmen - watchmen sitting on the floor next to eachother..   Format is: 
```
printf( "L X %s %d %d %d %d %d\n", so->codename, timecode, sensor_id, acode, timeinsweep, length );
```
[hmd_up_in_middle.txt.zip](https://github.com/cnlohr/libsurvive/files/721693/hmd_up_in_middle.txt.zip)

Then, using the above data, this me moving the HMD around after starting in the same position.  Try to track this!
[moving_hmd_from_start_in_up_in_middle.txt.zip](https://github.com/cnlohr/libsurvive/files/721694/moving_hmd_from_start_in_up_in_middle.txt.zip)

Try my data processor.  Check in the tools folder, tools/process_rawcap! It'll give you what you need to process it and get standard of deviation, etc.  For this data set, here is the output: 
[processed_data.txt](https://github.com/cnlohr/libsurvive/files/725788/processed_data.txt)

Pauls Test (Start at one position then move thing up 1 meter.) : 
[test_for_paul_start_at_position_then_go_up_1M.csv.zip](https://github.com/cnlohr/libsurvive/files/671669/test_for_paul_start_at_position_then_go_up_1M.csv.zip)

------ Relationship between distance and pulse length.
![measured difference between angle and distance](https://cloud.githubusercontent.com/assets/2748168/21489490/408b470c-cbb9-11e6-9948-854e786100a4.PNG)

[Relationship between Distance And Pulse Length.xlsx](https://github.com/cnlohr/libsurvive/files/673513/Relationship.between.Distance.And.Pulse.Length.xlsx)

**Comment by wasdennnoch** [comment]
Screenie from the stream http://puu.sh/tODMa/72d2b565c9.jpg

**Comment by mateon1** [comment]
HTC vive coordinate reference: ![](https://ipfs.io/ipfs/QmZAu2WSoVgc5c5h4cUWZafu5yH7wQJiqYTXy41WJYryyr)
Screenshot 2: ![](https://ipfs.io/ipfs/QmcX8mT5F3Hrnv6u4Mwg6w4Zz1AJ4hckffdizP7dG2a2be)

**Comment by cnlohr** [comment]
Fresh datas from the calibrator....  (With Josh's vive, need to find his cal data)

[ptinfo.csv.zip](https://github.com/cnlohr/libsurvive/files/815531/ptinfo.csv.zip)

Format is:
```fprintf( ptinfo, "%d %d %d %d %f %f %f %f %f %f\n", sen, lh, axis, count, avgsweep, avglen*1000000, stddevang*1000000000, stddevlen*1000000000, max_outlier_length*1000000000, max_outlier_angle*1000000000 );```

**Comment by cnlohr** [comment]
Object poses taken for HMD, WM1 and WM0 based on Charles Poser...

Distances from LH1, LH2 to object
3.85, 2.96
3.75, 3.8
3.2, 3.55

[objposes.csv.zip](https://github.com/cnlohr/libsurvive/files/840354/objposes.csv.zip)

**Comment by cnlohr** [comment]
Another test, this one is better than the above one.  It includes information about distances from lighthouses to objects.
[full_test_triangle_on_floor.zip](https://github.com/cnlohr/libsurvive/files/853966/full_test_triangle_on_floor.zip)

**Comment by mwturvey** [comment]
![image](https://cloud.githubusercontent.com/assets/18567877/24383791/1525a0ec-1314-11e7-91e3-e7d5b0e10742.png)

**Comment by mwturvey** [comment]
![image](https://cloud.githubusercontent.com/assets/18567877/24419207/401c2868-13a3-11e7-900e-169f7806c047.png)

**Comment by cnlohr** [comment]
Our definitions of +z is confusing to me now.  Is +Z down when holding the controller upright?

**Comment by mwturvey** [comment]
Yeah, I was surprised by this.  That's from IMU data.  (I assume/ hope that the config data uses the same reference frame as the IMU).  When you hold the controller horizontal, with the word "Vive" facing up, positive Z is facing the floor.

**Comment by mwturvey** [comment]
I just double checked the model of the tracker, and +Z from the model appears to be the same as what I got from the IMU.  Given that, I'm confident in the tracker's designation above.  And given that I used the same methodology for the controller, I'm pretty sure it's correct, too.  Once my HMD shows up in the mail, I'll verify against it using the same method, just to be sure.

**Comment by mwturvey** [comment]
Here's another sample, this time with just a single watchman that was connected via USB.  

One lighthouse is about 6 feet off the floor, the other is about 5 feet off the floor (~ 1.8m and 1.5 m).  The controller is roughly 2.5m away from each lighthouse.  Both lighthouses are placed on opposite sides of the same wall, about 3m apart.  This sample is using my disambiguator.

[calinfo.zip](https://github.com/cnlohr/libsurvive/files/1003286/calinfo.zip)

[output.zip](https://github.com/cnlohr/libsurvive/files/1003295/output.zip)

**Comment by mwturvey** [comment]
![image](https://user-images.githubusercontent.com/18567877/37250779-013c7668-24c1-11e8-86fa-fef017c5ee97.png)

**Comment by cnlohr** [comment]
here's some more data...  from HMD only.  (This is just light data, strictly.  For Charles and his new disambiguator experiment)

[lightdata.txt.zip](https://github.com/cnlohr/libsurvive/files/1813965/lightdata.txt.zip)

**Comment by cnlohr** [comment]
Here's a graph I made of distance from lighthouse and an incident angle.
[Relationship between Distance And Pulse Length.ods.zip](https://github.com/cnlohr/libsurvive/files/1840195/Relationship.between.Distance.And.Pulse.Length.ods.zip)
 some

**Comment by cnlohr** [comment]
Here is a set of data logs from the orange pi, no calibration, no posers.

[orange_pi_data_logs.zip](https://github.com/cnlohr/libsurvive/files/1844104/orange_pi_data_logs.zip)

**Comment by cnlohr** [comment]
Here's a pure lightcap...
[time] [sensor] [length] [tick]
[lightcap-orangepi-slow-fast-on-floor-three.txt.zip](https://github.com/cnlohr/libsurvive/files/1844152/lightcap-orangepi-slow-fast-on-floor-three.txt.zip)

**Comment by jdavidberger** [comment]
[lightcap-reformat.zip](https://github.com/cnlohr/libsurvive/files/1845699/lightcap-reformat.zip)

Same thing as lightcap-orangepi-slow-fast-on-floor-three.txt.zip but in a format that can be used as a playback file

**Comment by jdavidberger** [comment]
![screenshot from 2018-03-25 16-00-58](https://user-images.githubusercontent.com/8194827/37885225-3dc2ed18-3071-11e8-9952-ed7bd46e4221.png)
![screenshot from 2018-03-25 21-13-10](https://user-images.githubusercontent.com/8194827/37885258-6937575e-3071-11e8-91a9-f0a830eb4311.png)
[cleaner_data.zip](https://github.com/cnlohr/libsurvive/files/1846217/cleaner_data.zip)

Cleaner / debugged data with pictures. Note that things get very squirrely when you get too close to the sensor, but otherwise it follows what you'd expect

**Comment by cnlohr** [comment]
[data_for_albino.zip](https://github.com/cnlohr/libsurvive/files/1866126/data_for_albino.zip)

This is a data record sitting on the floor, pointed upward, then picking the vive up and moving around very slowly, going to the extremes of the lighthouses.

**Comment by jdavidberger** [comment]
Visualization for calibration values. 

I'm mostly adding these so I can link them in the wiki

**Comment by jdavidberger** [comment]
[logs_for_calibration.zip](https://github.com/cnlohr/libsurvive/files/1866913/logs_for_calibration.zip)

[calibration_pass.tar.xz.zip](https://github.com/cnlohr/libsurvive/files/1866924/calibration_pass.tar.xz.zip)
Rename that last one to omit the zip -- github doesn't like tar.xz?
